# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYDAmRg31LQnFFJ-MoaeeoxhVWhrr-Ac
"""

import pandas as pd
from pytrends.request import TrendReq
import matplotlib.pyplot as plt
trends = TrendReq()

pip install pytrends

import pandas as pd
from pytrends.request import TrendReq
import matplotlib.pyplot as plt
trends = TrendReq()

trends.build_payload(kw_list=["Block chain"])
data = trends.interest_by_region()
data = data.sort_values(by="Block chain", ascending=False)
data = data.head(10)
print(data)

data.reset_index().plot(x="geoName",
                        y="Block chain",
                        figsize=(15,12), kind="bar")
plt.style.use('fivethirtyeight')
plt.show()



data = TrendReq(hl='en-US', tz=360)
data.build_payload(kw_list=['Block chain'])
data = data.interest_over_time()
fig, ax = plt.subplots(figsize=(15, 12))
data['Block chain'].plot()
plt.style.use('fivethirtyeight')
plt.title('Total Google Searches for Block chain',
          fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Total Count')
plt.show()